#!/bin/sh

### BEGIN INIT INFO
# Provides:	        tcsd	
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:	        0 1 6
# Short-Description:    Start tcsd	
# Description: Just start the tcsd service
### END INIT INFO

set -e

do_start() {
	modprobe tpm_tis force=1 interrupts=0 > /dev/null 2>&1
	sleep 1
	modprobe tpm_tis force=1 interrupts=0 > /dev/null 2>&1
	sleep 1
	modprobe tpm_tis force=1 interrupts=0 > /dev/null 2>&1

	/usr/bin/tcsd &
}


case "$1" in
    start)
         do_start
         ;;
    stop)
         ;;
    restart)
         ;;
    reload)
         ;;
    force-reload)
         ;;
    status)
         ;;
    *)
     echo "$0 {start|stop|restart|reload|force-reload|status}"
esac

exit 0
